services:
  postgres:
    image: postgres:17-alpine
    container_name: orbit_tracker_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orbit_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: orbit_tracker_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  orbittracker:
    image: orbittracker
    build:
      context: .
      dockerfile: src/OrbitTracker.Api/Dockerfile
    container_name: orbit_tracker_api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=orbit_tracker;Username=postgres;Password=postgres"
      Redis__Host: "redis"
      Redis__Port: "6379"
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:

